name: "BB-CI: Build and Test"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Forge Lint
    uses: itsshantanu/gha-utils/.github/workflows/evm-lint.yml@main
    secrets: inherit

  build:
    name: Forge Build
    uses: itsshantanu/gha-utils/.github/workflows/forge-build.yml@main
    secrets: inherit

  test-invariant:
    needs: ["lint", "build"]
    uses: itsshantanu/gha-utils/.github/workflows/forge-test.yml@main
    with:
      foundry-invariant-depth: ${{ fromJSON(inputs.invariantDepth || '100') }}
      foundry-invariant-runs: ${{ fromJSON(inputs.invariantRuns || '100') }}
      foundry-profile: "test-optimized"
      match-path: "tests/invariant/**/*.sol"
      name: "Invariant tests"
