name: "CI Slither"

on:
  schedule:
    - cron: "0 3 * * 0" # at 3:00am UTC every Sunday

jobs:
  lint:
    uses: "onlyonejmjq/gha-utils/.github/workflows/evm-lint.yml@main"

  slither-analyze:
    needs: "lint"
    uses: "onlyonejmjq/gha-utils/.github/workflows/slither-analyze.yml@main"
